### ISSUE TITLE
map_mergerの使用時、環境地図画像が正しく表示されない

### ISSUE THREAD

**Issue by shunsugar** [KBKN-Autonomous-Robotics-Lab/multi_map_manager#2]
![Screenshot from 2023-11-01 14-59-34](https://github.com/KBKN-Autonomous-Robotics-Lab/multi_map_manager/assets/120554165/8db44a27-675a-4519-ad94-1ce1c92a3993)

Wikiの手順通り、環境地図を読み込みましたが、上の画像のように、環境地図画像が正しく表示されませんでした。

手順通り読み込んだファイルは、
・mymap.yaml, waypoints.yaml
・mymap1.yaml, waypoints1.yaml
で、Base map, Additional mapの順です。

また、mymap.pgm, mymap1.pgmはそれぞれ違う画像でした。

自分ではどこが間違っているのか見つけられなかったため、質問させていただきます。よろしくお願いいたします。
@koki0624

**Comment by koki0624** [comment]
読み込んだファイルの中身が分からないので推測ですが、下記のようにmymap1.yaml のファイル内で指定している画像ファイルが、mymap.pgm だったりしませんか？

```yaml
## mymap1.yaml

image: mymap.pgm  # 地図画像の絶対パスまたは相対パス。
...
```

**Comment by shunsugar** [comment]
その通りでした。ファイル名だけ変えて、ファイル内のmymap.pgmを変えていませんでした。
ありがとうございます！
